# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.5.0"
    }
  }
}

provider "google" {
  credentials = "/home/project/.sa_key"
  project = "cal-2831-87e766538bbd"
  region = "us-central1"
}
