region = "us-central1"
subnetwork_range = "10.0.0.0/16"
auto_create_subnetworks = "false"
machine_type = "f1-micro"
zone = "us-central1-a"
image = "debian-cloud/debian-10"
service_name = "web-service"
container_image = "us-central1-docker.pkg.dev/era-ax/infra/init:latest"